mainConfig:
  nickName:
    - "x"
  superUser:
    - 11111
  napcatUrl: ws://xxxxx
  napcatToken: xxx
cangmiaoKey: xxxx
db:
  host: 0.0.0.0
  port: 5432
  user: postgres
  password: xxx
  dbname: qqbot
